import { mkdirSync, mkdtempSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import { extractTurnImages } from "./turn-images.ts";

const IDS = Array.from({ length: 100 }, (_, i) => `123e4567-e89b-42d3-a456-${String(i).padStart(12, "0")}`);

describe("turn image admission", () => {
  const temporary: string[] = [];

  const store = (suffix = "") => {
    const root = mkdtempSync(join(tmpdir(), `omb-turn-images${suffix}-`));
    temporary.push(root);
    return root;
  };

  const image = (root: string, index: number, extension = ".png", bytes = 4) => {
    const path = join(root, `${IDS[index]}${extension}`);
    writeFileSync(path, Buffer.alloc(bytes, index + 1));
    return path;
  };

  afterEach(() => {
    for (const path of temporary.splice(0)) rmSync(path, { recursive: true, force: true });
  });

  it("turns standalone app-owned tags into structured images and keeps the source immutable", () => {
    const root = store();
    const png = image(root, 0, ".png", 7);
    const jpg = image(root, 1, ".jpg", 9);
    const source = [
      "compare these",
      "",
      `<attached-image path="${png}" name="first.png" />`,
      "",
      `<attached-image path="${jpg}" name="second.jpg" />`,
    ].join("\n");

    const result = extractTurnImages(source, { attachmentsDir: root });

    expect(source).toContain(png);
    expect(result.text).toBe("compare these\n\n\n\n");
    expect(result.images).toEqual([
      { path: png, mime: "image/png", bytes: 7 },
      { path: jpg, mime: "image/jpeg", bytes: 9 },
    ]);
    expect(result.text).not.toContain(root);
  });

  it("leaves inline, fenced, missing, outside-store, and non-generated tags as text", () => {
    const root = store();
    const outside = store("-outside");
    const valid = image(root, 0);
    const outsideImage = image(outside, 1);
    const ordinary = join(root, "ordinary.png");
    writeFileSync(ordinary, "not generated by the attachment store");
    const source = [
      `Example: <attached-image path="${valid}" />`,
      "```xml",
      `<attached-image path="${valid}" />`,
      "```",
      `<attached-image path="${join(root, `${IDS[2]}.png`)}" />`,
      `<attached-image path="${outsideImage}" />`,
      `<attached-image path="${ordinary}" />`,
    ].join("\n");

    expect(extractTurnImages(source, { attachmentsDir: root })).toEqual({ text: source, images: [] });
  });

  it("decodes composer entities once before validating the exact store path", () => {
    const parent = store();
    const root = join(parent, "images&more");
    mkdirSync(root);
    const path = image(root, 0, ".webp", 5);
    const encoded = path.replaceAll("&", "&amp;");

    expect(extractTurnImages(`<attached-image path="${encoded}" />`, { attachmentsDir: root })).toEqual({
      text: "",
      images: [{ path, mime: "image/webp", bytes: 5 }],
    });
  });

  it("rejects count and aggregate limits before partially stripping the prompt", () => {
    const root = store();
    const first = image(root, 0, ".png", 4);
    const second = image(root, 1, ".gif", 4);
    const source = `<attached-image path="${first}" />\n\n<attached-image path="${second}" />`;

    expect(() => extractTurnImages(source, { attachmentsDir: root, maxCount: 1 })).toThrow(
      "Send no more than 1 images",
    );
    expect(() => extractTurnImages(source, { attachmentsDir: root, maxBytes: 7 })).toThrow(
      "Attached images exceed 0.000007 MB total",
    );
  });

  it("accepts 30 by default and higher configured limits without truncating images", () => {
    const root = store();
    const paths = Array.from({ length: 75 }, (_, index) => image(root, index));
    const source = (count: number) => paths.slice(0, count).map(path => `<attached-image path="${path}" />`).join("\n\n");
    expect(extractTurnImages(source(30), { attachmentsDir: root }).images).toHaveLength(30);
    expect(() => extractTurnImages(source(31), { attachmentsDir: root })).toThrow("30 images");
    expect(extractTurnImages(source(75), { attachmentsDir: root, maxCount: 100_000, maxBytes: 1_000_000_000_000 }).images).toHaveLength(75);
  });

  it("does not admit a symlink carrying an attachment-shaped name", () => {
    const root = store();
    const outside = store("-target");
    const target = image(outside, 0);
    const link = join(root, `${IDS[1]}.png`);
    symlinkSync(target, link);
    const source = `<attached-image path="${link}" />`;

    expect(extractTurnImages(source, { attachmentsDir: root })).toEqual({ text: source, images: [] });
  });
});
